# ===== CONFIGURACIÓN GENERAL =====
version: '3.8'              # Versión de Docker Compose (como la versión de un programa)

services:                   # "Servicios" = contenedores que vas a crear

  # ===== CONTENEDOR DEL BACKEND =====
  backend:                  # Nombre del servicio (puede ser cualquier nombre)
    build: ./backend        # "Construye usando la carpeta ./backend" (busca Dockerfile ahí)
    container_name: facturas-backend  # Nombre que verás cuando hagas "docker ps"
    ports:
      - "3600:3600"         # "Puerto 3600 de tu PC → Puerto 3600 del contenedor"
    environment:            # Variables de entorno (como el .env)
      - NODE_ENV=development          # Le dice al contenedor que está en desarrollo
      - DB_HOST=mysql                 # "Conecta a la base de datos llamada 'mysql'"
      - DB_USER=admin                 # Usuario de la base de datos
      - DB_PASSWORD=1984endifR€%      # Password de la base de datos  
      - DB_DATABASE=db_jose           # Nombre de tu base de datos
    volumes:                # "Carpetas compartidas" (hot reload)
      - ./backend/src:/app/src        # "Tu carpeta src → carpeta src del contenedor"
      - ./backend/routes:/app/routes  # "Tus rutas → rutas del contenedor"
      - ./backend/index.js:/app/index.js  # "Tu index.js → index.js del contenedor"
    depends_on:             # "Espera a que este servicio esté listo antes de iniciar"
      - mysql               # "No inicies backend hasta que mysql esté funcionando"

  # ===== CONTENEDOR DEL FRONTEND =====  
  frontend:                 # Nombre del servicio
    build: ./frontend       # "Construye usando la carpeta ./frontend"
    container_name: facturas-frontend  # Nombre visible
    ports:
      - "4200:4200"         # "Puerto 4200 de tu PC → Puerto 4200 del contenedor"
    volumes:                # Hot reload para Angular
      - ./frontend/src:/app/src       # "Tu código Angular → código en el contenedor"

  # ===== CONTENEDOR DE MYSQL =====
  mysql:                    # Nombre del servicio
    image: mysql:8.0        # "Usa la imagen oficial de MySQL versión 8.0"
    container_name: facturas-mysql    # Nombre visible
    ports:
      - "3306:3306"         # "Puerto 3306 de tu PC → Puerto 3306 del contenedor"
    environment:            # Configuración de MySQL
      MYSQL_ROOT_PASSWORD: root       # Password del usuario root
      MYSQL_DATABASE: db_jose         # Crear base de datos "db_jose" automáticamente
      MYSQL_USER: admin               # Crear usuario "admin"
      MYSQL_PASSWORD: 1984endifR€%    # Password del usuario "admin"
    volumes:                # Almacenamiento persistente
      - mysql_data:/var/lib/mysql     # "Guardar datos en volumen mysql_data"

# ===== ALMACENAMIENTO PERSISTENTE =====
volumes:                    # Define volúmenes (espacios de almacenamiento)
  mysql_data:               # Nombre del volumen (para que los datos de MySQL no se pierdan)